// ============================================================
// APPSITE ERP – B2A Engenharia – Mock Data
// ============================================================

import type {
  Obra,
  TipoServico,
  ObraTipoServico,
  Equipe,
  Empreiteiro,
  AtividadePadrao,
  ContratoEmpreiteiro,
  ContratoItem,
  Medicao,
  Pendencia,
  Material,
  SolicitacaoMaterial,
  Fornecedor,
  Cotacao,
  CotacaoItemFornecedor,
  PedidoCompra,
  CronogramaEtapa,
} from "./types";

// ---- Obras ----
export const obras: Obra[] = [
  {
    id_obra: "OBR-001",
    nome_obra: "Residencial Parque das Flores",
    data_inicio_prevista: "2025-01-15",
    data_fim_prevista: "2026-06-30",
    status_obra: "Em Execução",
    gerente_obra: "Eng. Carlos Mendes",
    risco_obra: "Atenção",
    percentual_fisico_atual: 42,
    endereco: "Rua das Acácias, 500 – Bairro Jardim, SP",
  },
  {
    id_obra: "OBR-002",
    nome_obra: "Galpão Industrial Zona Norte",
    data_inicio_prevista: "2025-03-01",
    data_fim_prevista: "2025-12-31",
    status_obra: "Em Execução",
    gerente_obra: "Eng. Ana Paula Souza",
    risco_obra: "Crítico",
    percentual_fisico_atual: 68,
    endereco: "Av. Industrial, 1200 – Zona Norte, SP",
  },
  {
    id_obra: "OBR-003",
    nome_obra: "Reforma Sede Administrativa",
    data_inicio_prevista: "2025-06-01",
    data_fim_prevista: "2025-09-30",
    status_obra: "Concluída",
    gerente_obra: "Eng. Roberto Lima",
    risco_obra: "Normal",
    percentual_fisico_atual: 100,
    endereco: "Rua Central, 45 – Centro, SP",
  },
  {
    id_obra: "OBR-004",
    nome_obra: "Condomínio Vista Verde – Fase 2",
    data_inicio_prevista: "2026-02-01",
    data_fim_prevista: "2027-08-31",
    status_obra: "Planejada",
    gerente_obra: "Eng. Carlos Mendes",
    risco_obra: "Normal",
    percentual_fisico_atual: 0,
    endereco: "Estrada do Campo, km 12 – Cotia, SP",
  },
];

// ---- Tipos de Serviço ----
export const tiposServico: TipoServico[] = [
  { id_tipo_servico: "TS-001", descricao: "Valeteiro", ativo: true },
  { id_tipo_servico: "TS-002", descricao: "Armador", ativo: true },
  { id_tipo_servico: "TS-003", descricao: "Pedreiro", ativo: true },
  { id_tipo_servico: "TS-004", descricao: "Eletricista", ativo: true },
  { id_tipo_servico: "TS-005", descricao: "Encanador", ativo: true },
  { id_tipo_servico: "TS-006", descricao: "Pintor", ativo: true },
  { id_tipo_servico: "TS-007", descricao: "Carpinteiro", ativo: true },
];

// ---- Obras x Tipos de Serviço ----
export const obrasTiposServico: ObraTipoServico[] = [
  { id_obra_tipo_servico: "OTS-001", id_obra: "OBR-001", id_tipo_servico: "TS-001", peso_fisico: 20 },
  { id_obra_tipo_servico: "OTS-002", id_obra: "OBR-001", id_tipo_servico: "TS-002", peso_fisico: 30 },
  { id_obra_tipo_servico: "OTS-003", id_obra: "OBR-001", id_tipo_servico: "TS-003", peso_fisico: 25 },
  { id_obra_tipo_servico: "OTS-004", id_obra: "OBR-001", id_tipo_servico: "TS-006", peso_fisico: 15 },
  { id_obra_tipo_servico: "OTS-005", id_obra: "OBR-002", id_tipo_servico: "TS-001", peso_fisico: 25 },
  { id_obra_tipo_servico: "OTS-006", id_obra: "OBR-002", id_tipo_servico: "TS-002", peso_fisico: 35 },
  { id_obra_tipo_servico: "OTS-007", id_obra: "OBR-002", id_tipo_servico: "TS-004", peso_fisico: 40 },
];

// ---- Empreiteiros ----
export const empreiteiros: Empreiteiro[] = [
  {
    id_empreiteiro: "EMP-001",
    nome_fantasia: "Geneses Construções",
    razao_social: "Geneses Construções Ltda",
    cnpj: "12.345.678/0001-90",
    telefone: "(11) 99999-1111",
    ativo: true,
  },
  {
    id_empreiteiro: "EMP-002",
    nome_fantasia: "Armação Forte",
    razao_social: "Armação Forte Serviços ME",
    cpf_responsavel: "123.456.789-00",
    telefone: "(11) 98888-2222",
    ativo: true,
  },
  {
    id_empreiteiro: "EMP-003",
    nome_fantasia: "Elétrica Rápida",
    razao_social: "Elétrica Rápida Ltda",
    cnpj: "98.765.432/0001-10",
    telefone: "(11) 97777-3333",
    ativo: true,
  },
  {
    id_empreiteiro: "EMP-004",
    nome_fantasia: "Pintura Total",
    razao_social: "Pintura Total ME",
    telefone: "(11) 96666-4444",
    ativo: false,
  },
];

// ---- Equipes ----
export const equipes: Equipe[] = [
  { id_equipe: "EQ-001", id_empreiteiro: "EMP-001", nome_exibicao: "Geneses – Valeteiro – Equipe 01", ativo: true },
  { id_equipe: "EQ-002", id_empreiteiro: "EMP-001", nome_exibicao: "Geneses – Valeteiro – Equipe 02", ativo: true },
  { id_equipe: "EQ-003", id_empreiteiro: "EMP-002", nome_exibicao: "Armação Forte – Armador – Equipe 01", ativo: true },
  { id_equipe: "EQ-004", id_empreiteiro: "EMP-003", nome_exibicao: "Elétrica Rápida – Eletricista – Equipe 01", ativo: true },
];

// ---- Atividades Padrão ----
export const atividadesPadrao: AtividadePadrao[] = [
  { id_atividade_padrao: "AP-001", id_tipo_servico: "TS-001", descricao_atividade: "Abertura de valetas", unidade_medida: "m", ativo: true },
  { id_atividade_padrao: "AP-002", id_tipo_servico: "TS-001", descricao_atividade: "Abertura de tubulões", unidade_medida: "m", ativo: true },
  { id_atividade_padrao: "AP-003", id_tipo_servico: "TS-001", descricao_atividade: "Reaterro compactado", unidade_medida: "m³", ativo: true },
  { id_atividade_padrao: "AP-004", id_tipo_servico: "TS-002", descricao_atividade: "Armação de pilares", unidade_medida: "kg", ativo: true },
  { id_atividade_padrao: "AP-005", id_tipo_servico: "TS-002", descricao_atividade: "Armação de vigas", unidade_medida: "kg", ativo: true },
  { id_atividade_padrao: "AP-006", id_tipo_servico: "TS-002", descricao_atividade: "Armação de lajes", unidade_medida: "kg", ativo: true },
  { id_atividade_padrao: "AP-007", id_tipo_servico: "TS-003", descricao_atividade: "Alvenaria de vedação", unidade_medida: "m²", ativo: true },
  { id_atividade_padrao: "AP-008", id_tipo_servico: "TS-003", descricao_atividade: "Reboco interno", unidade_medida: "m²", ativo: true },
  { id_atividade_padrao: "AP-009", id_tipo_servico: "TS-006", descricao_atividade: "Pintura interna – 2 demãos", unidade_medida: "m²", ativo: true },
  { id_atividade_padrao: "AP-010", id_tipo_servico: "TS-006", descricao_atividade: "Pintura externa – 3 demãos", unidade_medida: "m²", ativo: true },
];

// ---- Contratos ----
export const contratos: ContratoEmpreiteiro[] = [
  {
    id_contrato: "CTR-001",
    numero_contrato: "B2A-2025-0001",
    id_obra: "OBR-001",
    id_empreiteiro: "EMP-001",
    id_tipo_servico: "TS-001",
    data_inicio: "2025-01-20",
    data_fim: "2025-06-30",
    tipo_contrato: "Unitário",
    valor_total_contratado: 85000,
    valor_total_medido: 51000,
    status_contrato: "Em Medição",
  },
  {
    id_contrato: "CTR-002",
    numero_contrato: "B2A-2025-0002",
    id_obra: "OBR-001",
    id_empreiteiro: "EMP-002",
    id_tipo_servico: "TS-002",
    data_inicio: "2025-02-01",
    data_fim: "2025-08-31",
    tipo_contrato: "Unitário",
    valor_total_contratado: 120000,
    valor_total_medido: 48000,
    status_contrato: "Em Medição",
  },
  {
    id_contrato: "CTR-003",
    numero_contrato: "B2A-2025-0003",
    id_obra: "OBR-002",
    id_empreiteiro: "EMP-003",
    id_tipo_servico: "TS-004",
    data_inicio: "2025-03-15",
    data_fim: "2025-11-30",
    tipo_contrato: "Global",
    valor_total_contratado: 200000,
    valor_total_medido: 200000,
    status_contrato: "100% Medido",
  },
  {
    id_contrato: "CTR-004",
    numero_contrato: "B2A-2025-0004",
    id_obra: "OBR-001",
    id_empreiteiro: "EMP-001",
    id_tipo_servico: "TS-001",
    data_inicio: "2025-07-01",
    data_fim: "2025-12-31",
    tipo_contrato: "Unitário",
    valor_total_contratado: 45000,
    valor_total_medido: 0,
    status_contrato: "Aberto",
  },
];

// ---- Itens de Contrato ----
export const contratoItens: ContratoItem[] = [
  {
    id_item_contrato: "IC-001",
    id_contrato: "CTR-001",
    id_atividade_padrao: "AP-001",
    descricao_item: "Abertura de valetas – Bloco A",
    unidade_medida: "m",
    quantidade_contratada: 500,
    valor_unitario: 85,
    valor_total_contratado_item: 42500,
  },
  {
    id_item_contrato: "IC-002",
    id_contrato: "CTR-001",
    id_atividade_padrao: "AP-003",
    descricao_item: "Reaterro compactado – Bloco A",
    unidade_medida: "m³",
    quantidade_contratada: 250,
    valor_unitario: 170,
    valor_total_contratado_item: 42500,
  },
  {
    id_item_contrato: "IC-003",
    id_contrato: "CTR-002",
    id_atividade_padrao: "AP-004",
    descricao_item: "Armação de pilares – Pavimento Térreo",
    unidade_medida: "kg",
    quantidade_contratada: 8000,
    valor_unitario: 8.5,
    valor_total_contratado_item: 68000,
  },
  {
    id_item_contrato: "IC-004",
    id_contrato: "CTR-002",
    id_atividade_padrao: "AP-005",
    descricao_item: "Armação de vigas – Pavimento Térreo",
    unidade_medida: "kg",
    quantidade_contratada: 6000,
    valor_unitario: 8.67,
    valor_total_contratado_item: 52000,
  },
];

// ---- Medições ----
export const medicoes: Medicao[] = [
  {
    id_medicao: "MED-001",
    numero_medicao: "001",
    id_contrato: "CTR-001",
    periodo_inicio: "2025-01-20",
    periodo_fim: "2025-02-28",
    data_medicao: "2025-03-01",
    status_medicao: "Paga",
    valor_total: 17000,
  },
  {
    id_medicao: "MED-002",
    numero_medicao: "002",
    id_contrato: "CTR-001",
    periodo_inicio: "2025-03-01",
    periodo_fim: "2025-03-31",
    data_medicao: "2025-04-02",
    status_medicao: "Aprovada Engenheiro",
    valor_total: 17000,
  },
  {
    id_medicao: "MED-003",
    numero_medicao: "003",
    id_contrato: "CTR-001",
    periodo_inicio: "2025-04-01",
    periodo_fim: "2025-04-30",
    data_medicao: "2025-05-02",
    status_medicao: "Rascunho",
    valor_total: 17000,
  },
  {
    id_medicao: "MED-004",
    numero_medicao: "001",
    id_contrato: "CTR-002",
    periodo_inicio: "2025-02-01",
    periodo_fim: "2025-03-31",
    data_medicao: "2025-04-01",
    status_medicao: "Enviada Financeiro",
    valor_total: 48000,
  },
];

// ---- Pendências ----
export const pendencias: Pendencia[] = [
  {
    id_pendencia: "PEN-001",
    id_obra: "OBR-001",
    id_equipe: "EQ-001",
    tipo_pendencia: "Técnica",
    descricao: "Verificar alinhamento das valetas no Bloco B – desvio de 5cm identificado",
    responsavel: "Geneses – Valeteiro – Equipe 01",
    data_criacao: "2025-04-10",
    data_limite: "2025-04-17",
    status: "Em Análise",
    criticidade: "Alta",
  },
  {
    id_pendencia: "PEN-002",
    id_obra: "OBR-001",
    id_contrato: "CTR-002",
    tipo_pendencia: "Ajuste",
    descricao: "Retrabalho na armação do pilar P-12 – espaçamento incorreto dos estribos",
    responsavel: "Armação Forte – Armador – Equipe 01",
    data_criacao: "2025-04-08",
    data_limite: "2025-04-15",
    status: "Aberto",
    criticidade: "Alta",
  },
  {
    id_pendencia: "PEN-003",
    id_obra: "OBR-002",
    tipo_pendencia: "Material",
    descricao: "Falta de cabo elétrico 10mm² para continuidade da instalação",
    responsavel: "Elétrica Rápida – Eletricista – Equipe 01",
    data_criacao: "2025-04-12",
    data_limite: "2025-04-14",
    status: "Aberto",
    criticidade: "Alta",
  },
  {
    id_pendencia: "PEN-004",
    id_obra: "OBR-001",
    tipo_pendencia: "Tarefa combinada",
    descricao: "Reunião de alinhamento com empreiteiro sobre cronograma do Bloco C",
    responsavel: "Eng. Carlos Mendes",
    data_criacao: "2025-04-11",
    data_limite: "2025-04-20",
    status: "Aberto",
    criticidade: "Média",
  },
  {
    id_pendencia: "PEN-005",
    id_obra: "OBR-002",
    tipo_pendencia: "Problema",
    descricao: "Infiltração detectada na laje do 2º pavimento – necessita vistoria urgente",
    responsavel: "Eng. Ana Paula Souza",
    data_criacao: "2025-04-13",
    data_limite: "2025-04-14",
    status: "Aberto",
    criticidade: "Alta",
  },
  {
    id_pendencia: "PEN-006",
    id_obra: "OBR-001",
    tipo_pendencia: "Técnica",
    descricao: "Conferir nível do contrapiso – Apartamentos 101 a 110",
    responsavel: "Eng. Carlos Mendes",
    data_criacao: "2025-04-05",
    data_limite: "2025-04-30",
    status: "Resolvido",
    criticidade: "Baixa",
  },
];

// ---- Materiais ----
export const materiais: Material[] = [
  { id_material: "MAT-001", descricao: "Cimento CP-II 50kg", unidade_padrao: "sc", ativo: true },
  { id_material: "MAT-002", descricao: "Areia média lavada", unidade_padrao: "m³", ativo: true },
  { id_material: "MAT-003", descricao: "Brita 1", unidade_padrao: "m³", ativo: true },
  { id_material: "MAT-004", descricao: "Vergalhão CA-50 10mm", unidade_padrao: "kg", ativo: true },
  { id_material: "MAT-005", descricao: "Vergalhão CA-50 12.5mm", unidade_padrao: "kg", ativo: true },
  { id_material: "MAT-006", descricao: "Cabo elétrico 10mm²", unidade_padrao: "m", ativo: true },
  { id_material: "MAT-007", descricao: "Tijolo cerâmico 9x14x19", unidade_padrao: "mil", ativo: true },
  { id_material: "MAT-008", descricao: "Tinta acrílica branca 18L", unidade_padrao: "gl", ativo: true },
];

// ---- Solicitações de Material ----
export const solicitacoes: SolicitacaoMaterial[] = [
  {
    id_solicitacao: "SOL-001",
    id_obra: "OBR-001",
    id_material: "MAT-001",
    descricao_material_livre: "Cimento CP-II 50kg",
    quantidade: 200,
    unidade: "sc",
    urgencia: "Alta",
    status_solicitacao: "Em Cotação",
    data_criacao: "2025-04-10",
  },
  {
    id_solicitacao: "SOL-002",
    id_obra: "OBR-001",
    id_material: "MAT-004",
    descricao_material_livre: "Vergalhão CA-50 10mm",
    quantidade: 5000,
    unidade: "kg",
    urgencia: "Média",
    status_solicitacao: "Pedido Emitido",
    data_criacao: "2025-04-08",
  },
  {
    id_solicitacao: "SOL-003",
    id_obra: "OBR-002",
    id_material: "MAT-006",
    descricao_material_livre: "Cabo elétrico 10mm²",
    quantidade: 500,
    unidade: "m",
    urgencia: "Crítico",
    status_solicitacao: "Aberta",
    data_criacao: "2025-04-13",
  },
  {
    id_solicitacao: "SOL-004",
    id_obra: "OBR-001",
    id_material: "MAT-007",
    descricao_material_livre: "Tijolo cerâmico 9x14x19",
    quantidade: 10,
    unidade: "mil",
    urgencia: "Baixa",
    status_solicitacao: "Entregue",
    data_criacao: "2025-04-01",
  },
  {
    id_solicitacao: "SOL-005",
    id_obra: "OBR-002",
    id_material: "MAT-003",
    descricao_material_livre: "Brita 1",
    quantidade: 30,
    unidade: "m³",
    urgencia: "Média",
    status_solicitacao: "Aprovada",
    data_criacao: "2025-04-11",
  },
];

// ---- Fornecedores ----
export const fornecedores: Fornecedor[] = [
  { id_fornecedor: "FOR-001", nome: "Materiais Construção ABC", cnpj: "11.222.333/0001-44", telefone: "(11) 3333-1111", ativo: true },
  { id_fornecedor: "FOR-002", nome: "Distribuidora Norte Sul", cnpj: "55.666.777/0001-88", telefone: "(11) 3333-2222", ativo: true },
  { id_fornecedor: "FOR-003", nome: "Ferro & Aço Ltda", cnpj: "99.000.111/0001-22", telefone: "(11) 3333-3333", ativo: true },
];

// ---- Cotações ----
export const cotacoes: Cotacao[] = [
  {
    id_cotacao: "COT-001",
    id_solicitacao: "SOL-001",
    data_abertura: "2025-04-11",
    status_cotacao: "Em Análise",
  },
];

// ---- Itens de Cotação por Fornecedor ----
export const cotacoesItensFornecedor: CotacaoItemFornecedor[] = [
  {
    id_item_fornecedor: "CIF-001",
    id_cotacao: "COT-001",
    id_fornecedor: "FOR-001",
    descricao_item: "Cimento CP-II 50kg",
    quantidade: 200,
    unidade: "sc",
    valor_unitario: 32.5,
    valor_total_item: 6500,
  },
  {
    id_item_fornecedor: "CIF-002",
    id_cotacao: "COT-001",
    id_fornecedor: "FOR-002",
    descricao_item: "Cimento CP-II 50kg",
    quantidade: 200,
    unidade: "sc",
    valor_unitario: 30.9,
    valor_total_item: 6180,
  },
  {
    id_item_fornecedor: "CIF-003",
    id_cotacao: "COT-001",
    id_fornecedor: "FOR-003",
    descricao_item: "Cimento CP-II 50kg",
    quantidade: 200,
    unidade: "sc",
    valor_unitario: 31.5,
    valor_total_item: 6300,
  },
];

// ---- Pedidos de Compra ----
export const pedidosCompra: PedidoCompra[] = [
  {
    id_pedido: "PED-001",
    numero_pedido: "B2A-PC-2025-0001",
    id_cotacao: "COT-001",
    id_obra: "OBR-001",
    id_fornecedor_escolhido: "FOR-002",
    data_emissao: "2025-04-08",
    status_pedido: "Emitido",
    valor_total: 42500,
  },
];

// ---- Cronograma Etapas ----
export const cronogramaEtapas: CronogramaEtapa[] = [
  {
    id_etapa: "ET-001",
    id_obra: "OBR-001",
    id_obra_tipo_servico: "OTS-001",
    id_equipe_responsavel: "EQ-001",
    descricao_etapa: "Abertura de valetas – Bloco A",
    data_inicio_planejada: "2025-01-20",
    prazo_dias_uteis: 30,
    data_fim_planejada: "2025-03-03",
    data_inicio_real: "2025-01-20",
    data_fim_real: "2025-03-05",
    percentual_execucao: 100,
    status: "Concluído",
    peso_na_obra: 10,
  },
  {
    id_etapa: "ET-002",
    id_obra: "OBR-001",
    id_obra_tipo_servico: "OTS-001",
    id_equipe_responsavel: "EQ-002",
    descricao_etapa: "Abertura de valetas – Bloco B",
    data_inicio_planejada: "2025-03-04",
    prazo_dias_uteis: 25,
    data_fim_planejada: "2025-04-07",
    data_inicio_real: "2025-03-06",
    percentual_execucao: 65,
    status: "Atrasado",
    peso_na_obra: 10,
  },
  {
    id_etapa: "ET-003",
    id_obra: "OBR-001",
    id_obra_tipo_servico: "OTS-002",
    id_equipe_responsavel: "EQ-003",
    descricao_etapa: "Armação de pilares – Pavimento Térreo",
    data_inicio_planejada: "2025-02-01",
    prazo_dias_uteis: 45,
    data_fim_planejada: "2025-04-04",
    data_inicio_real: "2025-02-03",
    percentual_execucao: 80,
    status: "Em Execução",
    peso_na_obra: 15,
  },
  {
    id_etapa: "ET-004",
    id_obra: "OBR-001",
    id_obra_tipo_servico: "OTS-002",
    id_equipe_responsavel: "EQ-003",
    descricao_etapa: "Armação de vigas – Pavimento Térreo",
    data_inicio_planejada: "2025-04-05",
    prazo_dias_uteis: 30,
    data_fim_planejada: "2025-05-16",
    percentual_execucao: 0,
    status: "Planejado",
    peso_na_obra: 15,
  },
  {
    id_etapa: "ET-005",
    id_obra: "OBR-001",
    id_obra_tipo_servico: "OTS-003",
    descricao_etapa: "Alvenaria de vedação – Bloco A",
    data_inicio_planejada: "2025-03-10",
    prazo_dias_uteis: 40,
    data_fim_planejada: "2025-05-05",
    data_inicio_real: "2025-03-12",
    percentual_execucao: 55,
    status: "Em Execução",
    peso_na_obra: 12,
  },
  {
    id_etapa: "ET-006",
    id_obra: "OBR-002",
    id_obra_tipo_servico: "OTS-005",
    id_equipe_responsavel: "EQ-001",
    descricao_etapa: "Abertura de valas – Fundação",
    data_inicio_planejada: "2025-03-01",
    prazo_dias_uteis: 20,
    data_fim_planejada: "2025-03-28",
    data_inicio_real: "2025-03-01",
    data_fim_real: "2025-03-26",
    percentual_execucao: 100,
    status: "Concluído",
    peso_na_obra: 20,
  },
  {
    id_etapa: "ET-007",
    id_obra: "OBR-002",
    id_obra_tipo_servico: "OTS-007",
    id_equipe_responsavel: "EQ-004",
    descricao_etapa: "Instalação elétrica – Galpão Principal",
    data_inicio_planejada: "2025-04-01",
    prazo_dias_uteis: 60,
    data_fim_planejada: "2025-06-23",
    data_inicio_real: "2025-04-01",
    percentual_execucao: 70,
    status: "Em Execução",
    peso_na_obra: 40,
  },
];
